spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /api

# Keeping only storage configuration for file uploads
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  storage:
    bucket: ai-help-desk

gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:3000/auth/google/callback}

# Frontend configuration
frontend:
  url: ${FRONTEND_URL:http://localhost:3000}
